# permissions for end users to view microservices.
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  labels:
    app.kubernetes.io/name: clusterrole
    app.kubernetes.io/instance: microservice-viewer-role
    app.kubernetes.io/component: rbac
    app.kubernetes.io/created-by: microservice-operator
    app.kubernetes.io/part-of: microservice-operator
    app.kubernetes.io/managed-by: kustomize
  name: microservice-viewer-role
rules:
- apiGroups:
  - api.imran.dev.io
  resources:
  - microservices
  verbs:
  - get
  - list
  - watch
- apiGroups:
  - api.imran.dev.io
  resources:
  - microservices/status
  verbs:
  - get
